namespace AEAQuiz.Classes
{
    internal class MyColors
    {
        private static readonly Dictionary<string, Color> _colors = new()
        {
            { "AliceBlue", Color.FromUint(0xFFF0F8FF) },
            { "AntiqueWhite", Color.FromUint(0xFFFAEBD7) },
            { "Aqua", Color.FromUint(0xFF00FFFF) },
            { "Aquamarine", Color.FromUint(0xFF7FFFD4) },
            { "Azure", Color.FromUint(0xFFF0FFFF) },
            { "Beige", Color.FromUint(0xFFF5F5DC) },
            { "Bisque", Color.FromUint(0xFFFFE4C4) },
            { "Black", Color.FromUint(0xFF000000) },
            { "BlanchedAlmond", Color.FromUint(0xFFFFEBCD) },
            { "Blue", Color.FromUint(0xFF0000FF) },
            { "BlueViolet", Color.FromUint(0xFF8A2BE2) },
            { "Brown", Color.FromUint(0xFFA52A2A) },
            { "BurlyWood", Color.FromUint(0xFFDEB887) },
            { "CadetBlue", Color.FromUint(0xFF5F9EA0) },
            { "Chartreuse", Color.FromUint(0xFF7FFF00) },
            { "Chocolate", Color.FromUint(0xFFD2691E) },
            { "Coral", Color.FromUint(0xFFFF7F50) },
            { "CornflowerBlue", Color.FromUint(0xFF6495ED) },
            { "Cornsilk", Color.FromUint(0xFFFFF8DC) },
            { "Crimson", Color.FromUint(0xFFDC143C) },
            { "Cyan", Color.FromUint(0xFF00FFFF) },
            { "DarkBlue", Color.FromUint(0xFF00008B) },
            { "DarkCyan", Color.FromUint(0xFF008B8B) },
            { "DarkGoldenrod", Color.FromUint(0xFFB8860B) },
            { "DarkGray", Color.FromUint(0xFFA9A9A9) },
            { "DarkGreen", Color.FromUint(0xFF006400) },
            { "DarkGrey", Color.FromUint(0xFFA9A9A9) },
            { "DarkKhaki", Color.FromUint(0xFFBDB76B) },
            { "DarkMagenta", Color.FromUint(0xFF8B008B) },
            { "DarkOliveGreen", Color.FromUint(0xFF556B2F) },
            { "DarkOrange", Color.FromUint(0xFFFF8C00) },
            { "DarkOrchid", Color.FromUint(0xFF9932CC) },
            { "DarkRed", Color.FromUint(0xFF8B0000) },
            { "DarkSalmon", Color.FromUint(0xFFE9967A) },
            { "DarkSeaGreen", Color.FromUint(0xFF8FBC8F) },
            { "DarkSlateBlue", Color.FromUint(0xFF483D8B) },
            { "DarkSlateGray", Color.FromUint(0xFF2F4F4F) },
            { "DarkSlateGrey", Color.FromUint(0xFF2F4F4F) },
            { "DarkTurquoise", Color.FromUint(0xFF00CED1) },
            { "DarkViolet", Color.FromUint(0xFF9400D3) },
            { "DeepPink", Color.FromUint(0xFFFF1493) },
            { "DeepSkyBlue", Color.FromUint(0xFF00BFFF) },
            { "DimGray", Color.FromUint(0xFF696969) },
            { "DimGrey", Color.FromUint(0xFF696969) },
            { "DodgerBlue", Color.FromUint(0xFF1E90FF) },
            { "Firebrick", Color.FromUint(0xFFB22222) },
            { "FloralWhite", Color.FromUint(0xFFFFFAF0) },
            { "ForestGreen", Color.FromUint(0xFF228B22) },
            { "Fuchsia", Color.FromUint(0xFFFF00FF) },
            { "Gainsboro", Color.FromUint(0xFFDCDCDC) },
            { "GhostWhite",  Color.FromUint(0xFFF8F8FF) },
            { "Gold", Color.FromUint(0xFFFFD700) },
            { "Goldenrod", Color.FromUint(0xFFDAA520) },
            { "Gray", Color.FromUint(0xFF808080) },
            { "Green", Color.FromUint(0xFF008000) },
            { "GreenYellow", Color.FromUint(0xFFADFF2F) },
            { "Grey", Colors.Gray },
            { "Honeydew", Color.FromUint(0xFFF0FFF0) },
            { "HotPink", Color.FromUint(0xFFFF69B4) },
            { "IndianRed", Color.FromUint(0xFFCD5C5C) },
            { "Indigo", Color.FromUint(0xFF4B0082) },
            { "Ivory", Color.FromUint(0xFFFFFFF0) },
            { "Khaki", Color.FromUint(0xFFF0E68C) },
            { "Lavender", Color.FromUint(0xFFE6E6FA) },
            { "LavenderBlush", Color.FromUint(0xFFFFF0F5) },
            { "LawnGreen", Color.FromUint(0xFF7CFC00) },
            { "LemonChiffon", Color.FromUint(0xFFFFFACD) },
            { "LightBlue", Color.FromUint(0xFFADD8E6) },
            { "LightCoral", Color.FromUint(0xFFF08080) },
            { "LightCyan", Color.FromUint(0xFFE0FFFF) },
            { "LightGoldenrodYellow", Color.FromUint(0xFFFAFAD2) },
            { "LightGray", Color.FromUint(0xFFD3D3D3) },
            { "LightGreen ", Color.FromUint(0xFF90EE90) },
            { "LightGrey", Colors.LightGray },
            { "LightPink", Color.FromUint(0xFFFFB6C1) },
            { "LightSalmon", Color.FromUint(0xFFFFA07A) },
            { "LightSeaGreen", Color.FromUint(0xFF20B2AA) },
            { "LightSkyBlue", Color.FromUint(0xFF87CEFA) },
            { "LightSlateGrey", Colors.LightSlateGray },
            { "LightSteelBlue", Color.FromUint(0xFFB0C4DE) },
            { "LightYellow", Color.FromUint(0xFFFFFFE0) },
            { "Lime", Color.FromUint(0xFF00FF00) },
            { "LimeGreen", Color.FromUint(0xFF32CD32) },
            { "Linen", Color.FromUint(0xFFFAF0E6) },
            { "Magenta", Color.FromUint(0xFFFF00FF) },
            { "Maroon", Color.FromUint(0xFF800000) },
            { "MediumAquamarine", Color.FromUint(0xFF66CDAA) },
            { "MediumBlue", Color.FromUint(0xFF0000CD) },
            { "MediumOrchid", Color.FromUint(0xFFBA55D3) },
            { "MediumPurple", Color.FromUint(0xFF9370D8) },
            { "MediumSeaGreen", Color.FromUint(0xFF3CB371) },
            { "MediumSlateBlue", Color.FromUint(0xFF7B68EE) },
            { "MediumSpringGreen", Color.FromUint(0xFF00FA9A) },
            { "MediumTurquoise", Color.FromUint(0xFF48D1CC) },
            { "MediumVioletRed", Color.FromUint(0xFFC71585) },
            { "MidnightBlue", Color.FromUint(0xFF191970) },
            { "MintCream", Color.FromUint(0xFFF5FFFA) },
            { "MistyRose", Color.FromUint(0xFFFFE4E1) },
            { "Moccasin", Color.FromUint(0xFFFFE4B5) },
            { "NavajoWhite", Color.FromUint(0xFFFFDEAD) },
            { "Navy", Color.FromUint(0xFF000080) },
            { "OldLace", Color.FromUint(0xFFFDF5E6) },
            { "Olive", Color.FromUint(0xFF808000) },
            { "OliveDrab", Color.FromUint(0xFF6B8E23) },
            { "Orange", Color.FromUint(0xFFFFA500) },
            { "OrangeRed", Color.FromUint(0xFFFF4500) },
            { "Orchid", Color.FromUint(0xFFDA70D6) },
            { "PaleGoldenrod", Color.FromUint(0xFFEEE8AA) },
            { "PaleGreen", Color.FromUint(0xFF98FB98) },
            { "PaleTurquoise", Color.FromUint(0xFFAFEEEE) },
            { "PaleVioletRed", Color.FromUint(0xFFD87093) },
            { "PapayaWhip", Color.FromUint(0xFFFFEFD5) },
            { "PeachPuff", Color.FromUint(0xFFFFDAB9) },
            { "Peru", Color.FromUint(0xFFCD853F) },
            { "Pink", Color.FromUint(0xFFFFC0CB) },
            { "Plum", Color.FromUint(0xFFDDA0DD) },
            { "PowderBlue", Color.FromUint(0xFFB0E0E6) },
            { "Purple", Color.FromUint(0xFF800080) },
            { "Red", Color.FromUint(0xFFFF0000) },
            { "RosyBrown", Color.FromUint(0xFFBC8F8F) },
            { "RoyalBlue", Color.FromUint(0xFF4169E1) },
            { "SaddleBrown", Color.FromUint(0xFF8B4513) },
            { "Salmon", Color.FromUint(0xFFFA8072) },
            { "SandyBrown", Color.FromUint(0xFFF4A460) },
            { "SeaGreen", Color.FromUint(0xFF2E8B57) },
            { "SeaShell", Color.FromUint(0xFFFFF5EE) },
            { "Sienna ", Color.FromUint(0xFFA0522D) },
            { "Silver", Color.FromUint(0xFFC0C0C0) },
            { "SkyBlue", Color.FromUint(0xFF87CEEB) },
            { "SlateBlue", Color.FromUint(0xFF6A5ACD) },
            { "SlateGray", Color.FromUint(0xFF708090) },
            { "SlateGrey", Colors.SlateGray },
            { "Snow", Color.FromUint(0xFFFFFAFA) },
            { "SpringGreen", Color.FromUint(0xFF00FF7F) },
            { "SteelBlue", Color.FromUint(0xFF4682B4) },
            { "Tan", Color.FromUint(0xFFD2B48C) },
            { "Teal", Color.FromUint(0xFF008080) },
            { "Thistle", Color.FromUint(0xFFD8BFD8) },
            { "Tomato", Color.FromUint(0xFFFF6347) },
            { "Transparent", Color.FromUint(0x00000000) },
            { "Turquoise", Color.FromUint(0xFF40E0D0) },
            { "Violet", Color.FromUint(0xFFEE82EE) },
            { "Wheat", Color.FromUint(0xFFF5DEB3) },
            { "White", Color.FromUint(0xFFFFFFFF) },
            { "WhiteSmoke", Color.FromUint(0xFFF5F5F5) },
            { "Yellow", Color.FromUint(0xFFFFFF00) },
            { "YellowGreen", Color.FromUint(0xFF9ACD32) }
        };

        public static List<Color> GetColorList() => _colors.Values.ToList();

        public static Color GetRandom() 
        { 
            Random r = new();
            List<Color> colors = GetColorList();
            return colors[r.Next(colors.Count)];
        }

    }
}
